### PR TITLE
Diegom sobol

### PR DESCRIPTION
**Pull request by diegomartinez2**
The Sobol sampling is ready for a pull to merge into master. Note that it needs to pull both python-sscha and CellConstructor for Sobol to work.

### CODE REVIEW

**Comment by diegomartinez2** [comment]
This needs to be in the main code before the python-sscha Sobol code is added or the automatic check will fail.

**Review by mesonepigreco — APPROVED** [review]
It seems that the sobol is not hampering the good work of the cellconstructor

**Comment by mesonepigreco** [comment]
@diegomartinez2 
I started the merging process, however the automatic syntax check for the file found an error here:

```
./cellconstructor/Moro_object.py:127:18: F821 undefined name 'sobol_modes'
            x1 = sobol_modes(size = size, n_modes = 21201 , scramble = scramble)
                 ^
./cellconstructor/Moro_object.py:128:18: F821 undefined name 'sobol_big'
            x2 = sobol_big(size = size, n_modes = number, scramble = scramble)
                 ^
./cellconstructor/Moro_object.py:131:17: F821 undefined name 'sobol_modes'
            x = sobol_modes(size = size, n_modes = n_modes , scramble = scramble)
                ^
3     F821 undefined name 'sobol_modes'
3
```

Can you check and fix the error? Now every commit you do will automatically run the test, you can see the result here:
https://github.com/SSCHAcode/CellConstructor/actions

So if we merge this and then the python-sscha, we can release version 1.2

**Comment by diegomartinez2** [comment]
> @diegomartinez2 I started the merging process, however the automatic syntax check for the file found an error here:
> 
> ```
> ./cellconstructor/Moro_object.py:127:18: F821 undefined name 'sobol_modes'
>             x1 = sobol_modes(size = size, n_modes = 21201 , scramble = scramble)
>                  ^
> ./cellconstructor/Moro_object.py:128:18: F821 undefined name 'sobol_big'
>             x2 = sobol_big(size = size, n_modes = number, scramble = scramble)
>                  ^
> ./cellconstructor/Moro_object.py:131:17: F821 undefined name 'sobol_modes'
>             x = sobol_modes(size = size, n_modes = n_modes , scramble = scramble)
>                 ^
> 3     F821 undefined name 'sobol_modes'
> 3
> ```
> 
> Can you check and fix the error? Now every commit you do will automatically run the test, you can see the result here: https://github.com/SSCHAcode/CellConstructor/actions
> 
> So if we merge this and then the python-sscha, we can release version 1.2

I don't get why it gives an error, 'sobol_modes' function is defined right there in line 105.

**Comment by diegomartinez2** [comment]
We can comment the function 'sobol_big' where the error of the automatic syntax check is located, but that will set a limit on the number of vibrational modes to 21201.
On one hand is a big enough number of vibrational modes so we may remove the recursive function, on the other hand I still do not understand why it gives an error there.

**Comment by mesonepigreco** [comment]
Hi @diegomartinez2  , I think it is because the two functions are inside a class.
You should call them as self.sobol_model ... I think this way should fix

**Comment by diegomartinez2** [comment]
> Hi @diegomartinez2 , I think it is because the two functions are inside a class.
> You should call them as self.sobol_model ... I think this way should fix

Taking the function out passes the test.
I'll try next with "self.sobol_modes".

**Comment by mesonepigreco** [comment]
There is an indentation error:
./cellconstructor/Moro_object.py:123:131: E999 IndentationError: unindent does not match any outer indentation level
1     E999 IndentationError: unindent does not match any outer indentation level
1
Error: Process completed with e

**Pull request merged**
