### PR TITLE
Perturbative limit

### PR DESCRIPTION
**Pull request by DjordjeDangic**
Added a new perturbative limit for the non-diagonal lattice thermal conductivity and the perturbative limit for the AC thermal conductivity.

### CODE REVIEW

**Comment by mesonepigreco** [comment]
Hi @DjordjeDangic ,
Should I merge this? Or you want to delete the changes?

**Comment by DjordjeDangic** [comment]
If you can yes please merge it.

**Comment by mesonepigreco** [comment]
Ok, I performed the merge manually, however, the code auto check of syntax now crashes with the error

```
./cellconstructor/ThermalConductivity.py:1645:45: F821 undefined name 'ne'
            self.get_lifetimes(temperature, ne, gauss_smearing = gauss_smearing, isotope_scattering = isotope_scattering, isotopes = isotopes, method = lf_method)
``` 

To make things easier, you can try to act directly on the master of CellConstructor

**Comment by mesonepigreco** [comment]
I gave you write access to the repository

**Comment by DjordjeDangic** [comment]
Hey Lorenzo, can you merge now?

**Comment by mesonepigreco** [comment]
Merged. To avoid conflicts and allow easier merges, try pulling the master into your branch now (make a reverse pull request in your repository). This way, the two repositories get synchronized, and it should be very easy to do the auto merge.

**Pull request merged**
