### PR TITLE
Added test for the lattice thermal conductivity 

### PR DESCRIPTION
**Pull request by DjordjeDangic**
Added a test for the lattice thermal conductivity in tests/TestTC. Also changed the compilation flags for thermal conductivity which should quiet warnings during execution of the code (see #86 ).

### CODE REVIEW

**Comment by mesonepigreco** [comment]
Hi, it seems the test is failing because it does not find a file:
```
=========================== short test summary info ============================
FAILED tests/TestTC/test_tc.py::test_tc - ValueError: Error, file final_dyn1 does not exist.
====== 1 failed, 72 passed, 6 skipped, 1109 warnings in 358.39s (0:05:58) ======
```

Have you included it with git add?

**Comment by diegomartinez2** [comment]
Strange, I can see the file in tests/TestTC/final_dyn1

**Comment by diegomartinez2** [comment]
You need 
```
total_path = os.path.dirname(os.path.abspath(__file__))
os.chdir(total_path)
```

**Comment by mesonepigreco** [comment]
As Diego mentioned, you need to add those lines at the beginning of your testing function. This happens because the test executes all the Python files from the project's root, not from the directory in which the test is located. This way, the relative paths are broken. Those lines change the path for that script to the one in which the script is located, thus enabling you to use relative paths in your testing function.

**Comment by mesonepigreco** [comment]
Ok, test are passing! Can I merge?

**Comment by DjordjeDangic** [comment]
Yes, please.

**Pull request merged**
